PUT http://localhost:3003/api/blogs/5aa590cde40f0c3eb637a817
content-type: application/json

{
    "comments": [{"id":"12", "comment": "kommentti"}],
    "title": "uudempi kommenttitesti",
    "author": "kirjailija",
    "url": "ei urlia",
    "likes": 0
  }
